# @prompt username
# @prompt email
# @prompt password
POST http://localhost:3000/api/auth/login
Content-Type: application/json
origin : http://localhost:5173

{
  "username": "{{username}}",
  "email": "{{{email}}}",
  "password": "{{password}}"
}

### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json
origin: http://localhost:5173

{
  "username": "dean",
  "email": "dean@example.com",
  "password": "password1"
}

###
# @prompt title
# @prompt description
# @prompt latitude
# @prompt longitude
# @prompt photoUrl
POST  http://localhost:3000/api/auth/memory
Content-Type: application/json
Origin: http://localhost:5173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDNlNWU4Y2RjOGQ3ZDBkZDMwNmFhMSIsInVzZXJuYW1lIjoiZGVhbiIsImVtYWlsIjoiZGVhbkBleGFtcGxlLmNvbSIsImlhdCI6MTc1ODg4NjMwMSwiZXhwIjoxNzU5NDkxMTAxfQ.0CXVEM229PurtN0jEkc6IXTGkeoS12aTtFZeAsacx5o

{
  "title": "{{title}}",
  "description": "{{description}}",
 "location": {
    "lat": "{{latitude}}",
    "lng": "{{longitude}}"
  },
  "photoURL": "{{photoUrl}}"
}