# @prompt username
# @prompt email
# @prompt password
POST http://localhost:3000/api/auth/login
Content-Type: application/json
origin : http://localhost:5173

{
  "username": "{{username}}",
  "email": "{{{email}}}",
  "password": "{{password}}"
}

### Register User
POST http://localhost:3000/api/auth/register
Content-Type: application/json
origin: http://localhost:5173

{
  "username": "dencio",
  "email": "dencio@email.com",
  "password": "password1"
}